name: LifeStealSpawn
version: ${project.version}
main: com.jbes.lifestealspawn.LifeStealSpawnPlugin
api-version: '26.1.2'
authors:
  - JBES
description: clutchsmp spawn generator and protection plugin.

commands:
  generatespawn:
    description: Generate the clutchsmp spawn.
    usage: /generatespawn [confirm]
    permission: lifestealspawn.generate

permissions:
  lifestealspawn.generate:
    description: Allows generation of the clutchsmp spawn.
    default: op
